name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set timestamp variable
        run: echo "::set-env name=TIMESTAMP::$(date +%s)"
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag quyc07/chat-room:${{ env.TIMESTAMP }}
      - name: Push the Docker image
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push quyc07/chat-room:${{ env.TIMESTAMP }}
